In [127]:
import csv
import datetime
import pandas as pd 

from operator import itemgetter

tod = datetime.datetime.now()
last_three_weeks = (tod - datetime.timedelta(days = 21)).date()
last_two_weeks = (tod - datetime.timedelta(days = 14)).date()
last_week = (tod - datetime.timedelta(days = 7)).date()

by_date = []
test_three = {
        'name': 'Three Weeks',
        'last_seen': last_three_weeks - datetime.timedelta(days=1)
    }
test_two =     {
        'name': 'Two Weeks',
        'last_seen': last_two_weeks - datetime.timedelta(days=1)
    }
test_one = {
        'name': 'One Week',
        'last_seen': last_week - datetime.timedelta(days=1)
    }        
pax_last_seen = [
    test_one,
    test_two,
    test_three
]


with open('bb.csv', newline='', encoding='utf-8-sig') as csvfile:
    reader = csv.DictReader(csvfile)
    for row in reader:
        all_pax = row['PAX'].split(',')
        qic = row['QIC'].replace('and', ',').split(',')
        all_pax += qic
        when = datetime.datetime.strptime(row['When'], '%m/%d/%Y').date()
        
        for pax in all_pax:
            pax = pax.replace('(RESPECT)', '')
            pax = pax.strip()
            record = next((item for item in pax_last_seen if item['name'] == pax), None)
            if record:
                record['last_seen'] = when
            else:
                new_record = {
                    'name': pax,
                    'last_seen': when
                }
                pax_last_seen.append(new_record)

In [128]:
missing_one_week = [pax for pax in pax_last_seen if pax['last_seen'] < last_week and pax['last_seen'] > last_two_weeks]
pd.DataFrame(missing_one_week)

       name   last_seen
0  One Week  2022-02-23

In [129]:
missing_two_week = [pax for pax in pax_last_seen if pax['last_seen'] < last_two_weeks and pax['last_seen'] > last_three_weeks]
pd.DataFrame(missing_two_week)

              name   last_seen
0        Two Weeks  2022-02-16
1         TracFone  2022-02-14
2           Managu  2022-02-11
3             2Ply  2022-02-12
4       Amphibious  2022-02-12
5           Draper  2022-02-12
6     Fiddle Stick  2022-02-12
7         Foot Joy  2022-02-12
8           Misery  2022-02-12
9       FishNChips  2022-02-11
10  and four more!  2022-02-11
11     Haagen Dazs  2022-02-11

In [131]:
missing_three_week = [pax for pax in pax_last_seen if pax['last_seen'] < last_three_weeks]
pd.DataFrame(missing_three_week)

             name   last_seen
0     Three Weeks  2022-02-09
1    Larry Legend  2022-01-31
2    Sodapopinski  2021-12-22
3    Fresh Prince  2021-12-20
4         Chowdah  2021-12-20
..            ...         ...
388       LapLane  2021-12-13
389       RedTape  2021-12-13
390         Sonar  2021-12-13
391    Beaujolias  2021-12-14
392    Smoky bear  2021-12-14

[393 rows x 2 columns]